name: Check Linux Packages
on:
  push:
    paths:
      - 'linuxNew/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'linuxNew/**'

jobs:
  check-ca-certificates:
    name: "Check ca-certificates"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel :ca-certificates:check --stacktrace

  check-jdk-packages:
    name: "Check ${{ matrix.product.name }} ${{ matrix.product.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # No Docker on macOS
        # https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/8
        product: [
          { name: dragonwell, version: 11 },
          { name: temurin, version: 11 },
          { name: temurin, version: 16 },
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel check -PPRODUCT=${{ matrix.product.name }} -PPRODUCT_VERSION=${{ matrix.product.version }} --stacktrace

  # Ensures we don't accept a Gradle Wrapper update that has been tampered with.
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
